### ISSUE TITLE
Tif images are not supported.

### ISSUE THREAD

**Issue by jreuter** [jreuter/mediaResizer#4]
Traceback (most recent call last):
  File "./mediaResizer.py", line 241, in <module>
    MediaResizer().main()
  File "./mediaResizer.py", line 218, in main
    results = pool.map(unwrap_self, zip([self]*len(files), files))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
ValueError: Setting Image comment in TIFF images is not supported

I will need to research what if failing here and fix it.  It looks like some were created, but perhaps the EXIF data can not be applied.

**Comment by jreuter** [comment]
Fixed in PR: https://github.com/jreuter/mediaResizer/pull/9
